server:
  port: 8083
spring:
  application:
    name: BackEnd-client-Service
  cloud:
    gateway:
      routes:
        - id: Tariffs
          uri: http://${TARIFFS_HOST:localhost}:${TARIFFS_PORT:8082}
          predicates:
            - Path=/tariffs/**
        - id: Products
          uri: http://${PRODUCTS_HOST:localhost}:${PRODUCTS_PORT:8081}
          predicates:
            - Path=/products/**