server:
  port: 8083
spring:
  application:
    name: BackEnd-client-Service
  cloud:
    gateway:
      routes:
        - id: ClientAccount-service
          uri: http://${CLIENT_HOST:localhost}:${CLIENT_PORT:8080}
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/(?<segment>.*),/$\{segment}
        - id: Products-service
          uri: http://${PRODUCTS_HOST:localhost}:${PRODUCTS_PORT:8081}
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*),/$\{segment}
        - id: Tariffs-service
          uri: http://${TARIFFS_HOST:localhost}:${TARIFFS_PORT:8082}
          predicates:
            - Path=/tariffs/**
          filters:
            - RewritePath=/tariffs/(?<segment>.*),/$\{segment}
        - id: AuthValid-service
          uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:8084}
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*),/$\{segment}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /accounts/v3/api-docs
        name: ClientAccount-service
      - url: /products/v3/api-docs
        name: Products-service
      - url: /tariffs/v3/api-docs
        name: Tariffs-service
      - url: /auth/v3/api-docs
        name: AuthValid-service

